mv step_4delta.c covid_4delta.c
mv step_comms.c covid_comms.c
mv step_fastq.c covid_fastq.c
mv step_freqtime.c covid_freqtime.c
mv step_frequ.c covid_frequ.c
mv step_genotype.c covid_genotype.c
mv stepID.c covidID.c
mv stepID-old.c covidID-old.c
mv stepID-S2.c covidID-S2.c
mv step_lineage.c covid_lineage.c
mv step_metadata.c covid_metadata.c
mv step_months.c covid_months.c
mv step_names.c covid_names.c
mv step_nation.c covid_nation.c
mv step_nation-s.c covid_nation-s.c
mv step_number.c covid_number.c
mv step_Pangenome.c covid_Pangenome.c
mv stepPangenome.c covidPangenome.c
mv step_pca.c covid_pca.c
mv step_pca-old.c covid_pca-old.c
mv stepPileup.c covidPileup.c
mv step_sigfreq.c covid_sigfreq.c
mv step_sigsort.c covid_sigsort.c
mv stepSNP.c covidSNP.c
mv stepSNPcons.c covidSNPcons.c
mv stepSNP-H.c covidSNP-H.c
mv stepSNP-ID.c covidSNP-ID.c
mv stepSNP-old.c covidSNP-old.c
mv stepSNP-s.c covidSNP-s.c
mv stepSNP-sss.c covidSNP-sss.c
mv step_times.c covid_times.c
mv step_times-sample.c covid_times-sample.c
mv step_times-s.c covid_times-s.c
