mv covid_4delta.c step_4delta.c
mv covid_comms.c step_comms.c
mv covid_fastq.c step_fastq.c
mv covid_freqtime.c step_freqtime.c
mv covid_frequ.c step_frequ.c
mv covid_genotype.c step_genotype.c
mv covidID.c stepID.c
mv covidID-old.c stepID-old.c
mv covidID-S2.c stepID-S2.c
mv covid_lineage.c step_lineage.c
mv covid_metadata.c step_metadata.c
mv covid_months.c step_months.c
mv covid_names.c step_names.c
mv covid_nation.c step_nation.c
mv covid_nation-s.c step_nation-s.c
mv covid_number.c step_number.c
mv covid_Pangenome.c step_Pangenome.c
mv covidPangenome.c stepPangenome.c
mv covid_pca.c step_pca.c
mv covid_pca-old.c step_pca-old.c
mv covidPileup.c stepPileup.c
mv covid_sigfreq.c step_sigfreq.c
mv covid_sigsort.c step_sigsort.c
mv covidSNP.c stepSNP.c
mv covidSNPcons.c stepSNPcons.c
mv covidSNP-H.c stepSNP-H.c
mv covidSNP-ID.c stepSNP-ID.c
mv covidSNP-old.c stepSNP-old.c
mv covidSNP-s.c stepSNP-s.c
mv covidSNP-sss.c stepSNP-sss.c
mv covid_times.c step_times.c
mv covid_times-sample.c step_times-sample.c
mv covid_times-s.c step_times-s.c
